---
- hosts: localhost
  become: true
  tasks: null
- name: Deploy war file
  get_url: url=https://tomcat.apache.org/tomcat-8.5-doc/appdev/sample/sample.war
    dest=/opt/apache-tomcat/sample.war
- name: Deploy to tomcat folder
  command: mv /opt/apache-tomcat/sample.war
    /opt/apache-tomcat/apache-tomcat-8.5.87/webapps
